---
- name: Create Docker Group
  become: true
  group:
    name: docker
    state: present

- name: Ensure User Groups
  become: true
  user:
    name: "{{ user }}"
    groups:
      - docker
      - wheel
    state: present
    shell: /bin/bash

- name: Create ssh dir
  file:
    path: ~/.ssh/
    state: directory
    mode: '0755'

- name: Create ssh keypair
  openssh_keypair:
    path: ~/.ssh/id_rsa
    owner: "{{ user }}"
    type: rsa
    size: 4096
    state: present
    passphrase: "{{ ssh_passphrase }}"
