---
- name: Update system
  become: true
  package:
    update_cache: yes
    upgrade: yes
  when: ansible_facts['distribution'] != "Fedora"

- name: Update system
  become: true
  dnf:
    name: "*"
    state: latest
  when: ansible_facts['distribution'] == "Fedora"

- name: Install basic packages
  become: true
  package:
    name: "{{ packages }}"
    state: latest

- name: Install ueberzug
  pip:
    name: ueberzug

- name: Clone dotfiles
  git:
    repo: "{{ dotfiles }}"
    dest: dotfiles
    force: yes
    track_submodules: yes

- name: Set zsh as default shell
  become: true
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh

- name: Clone nvim config
  git:
    repo: "{{ nvim }}"
    dest: .config/nvim
    force: yes

- name: Install Vim-Plug
  shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

- name: Copy Nvim config for root user
  become: true
  shell: 'mkdir -p /root/.config/nvim/ && cp /home/{{ user }}/.config/nvim/base-init.vim /root/.config/nvim/'

- name: Unstow dotfiles
  shell:
    cmd: stow -R *
    chdir: dotfiles
