---

- name: Update system
  become: true
  package:
    update_cache: yes
    upgrade: yes

- name: Install basic packages
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ packages.cli }}"
    - "{{ packages.gui }}"
    - "{{ packages.nvim }}"
  ignore_errors: true
