---

- name: Update system
  become: true
  dnf:
    name: "*"
    state: latest

- name: Add Repos
  become: true
  shell: '{{ item }}'
  with_items:
    - 'dnf config-manager --add-repo https://raw.githubusercontent.com/rpmsphere/rpmsphere.github.io/master/rpmsphere.repo'
    - 'dnf config-manager --add-repo https://raw.githubusercontent.com/rpmsphere/rpmsphere.github.io/master/rpmsphere.repo'
    - 'sudo dnf copr enable atim/lazygit -y'
    - 'sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/'
    - 'sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc'

- name: Install basic packages
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ packages.cli }}"
    - "{{ packages.gui }}"
    - "{{ packages.nvim }}"
    - "{{ packages.rpm }}"
    - "{{ packages.npm }}"
  ignore_errors: true
